import Head from "next/head";

export const Eventos = () => {
    return (
        <div>
            <Head>
                <title>Eventos</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" sizes="350x350" href="/assets/favicon.png" />
            </Head>
            <h1>Eventos</h1>
        </div>
    )
}

export default Eventos;