import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>SID locações</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" type="image/png" sizes="350x350" href="/assets/favicon.png" />
			</Head>
			<main>
				<div className={styles.container}>
					<h1>HOME</h1>
				</div>
			</main>
		</>
	)
}
